import Head from "next/head";
import { useState } from "react";
import Layout from "../components/layout";
import TodoForm from "../components/todo/TodoForm";
import TodoList from "../components/todo/TodoList";

export default function Home() {
	const [todoList, setTodoList] = useState([]);
	return (
		<div>
			<Head>
				<title>Next Todo</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Layout>
				<div className="todo-container mx-auto bg-white rounded-xl h-full px-2 py-4">
					<TodoForm todoList={todoList} setTodoList={setTodoList} />
					<TodoList todoList={todoList} setTodoList={setTodoList} />
				</div>
			</Layout>

			<style jsx>
				{`
					.todo-container {
						width: 95%;
						max-width: 500px;
						min-width: 300px;
					}
				`}
			</style>
		</div>
	);
}
